CREATE DATABASE IF NOT EXISTS zenbu_users;

CREATE USER IF NOT EXISTS 'zenbu_admin'@'%' IDENTIFIED BY 'zenbu_admin';
GRANT SELECT, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE, ALTER, DELETE, INDEX, INSERT, UPDATE, SHOW DATABASES on *.* to 'zenbu_admin'@"%";

CREATE USER IF NOT EXISTS 'read'@'%' IDENTIFIED BY 'read';
 /* DO NOT do give read:read grants to the user database */

FLUSH PRIVILEGES;
